// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package iw.zvezdahotels.usuario;

import iw.zvezdahotels.usuario.UserRole;

privileged aspect UserRole_Roo_JavaBean {
    
    public String UserRole.getUserRole() {
        return this.userRole;
    }
    
    public void UserRole.setUserRole(String userRole) {
        this.userRole = userRole;
    }
    
}
