// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package iw.zvezdahotels;

import iw.zvezdahotels.Category;
import iw.zvezdahotels.CategoryDataOnDemand;
import iw.zvezdahotels.Hotel;
import iw.zvezdahotels.HotelDataOnDemand;
import iw.zvezdahotels.Room;
import iw.zvezdahotels.RoomDataOnDemand;
import iw.zvezdahotels.room.RoomState;
import iw.zvezdahotels.room.RoomType;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect RoomDataOnDemand_Roo_DataOnDemand {
    
    declare @type: RoomDataOnDemand: @Component;
    
    private Random RoomDataOnDemand.rnd = new SecureRandom();
    
    private List<Room> RoomDataOnDemand.data;
    
    @Autowired
    CategoryDataOnDemand RoomDataOnDemand.categoryDataOnDemand;
    
    @Autowired
    HotelDataOnDemand RoomDataOnDemand.hotelDataOnDemand;
    
    public Room RoomDataOnDemand.getNewTransientRoom(int index) {
        Room obj = new Room();
        setRCategory(obj, index);
        setRHotel(obj, index);
        setRNumber(obj, index);
        setRState(obj, index);
        setRType(obj, index);
        return obj;
    }
    
    public void RoomDataOnDemand.setRCategory(Room obj, int index) {
        Category rCategory = categoryDataOnDemand.getRandomCategory();
        obj.setRCategory(rCategory);
    }
    
    public void RoomDataOnDemand.setRHotel(Room obj, int index) {
        Hotel rHotel = hotelDataOnDemand.getRandomHotel();
        obj.setRHotel(rHotel);
    }
    
    public void RoomDataOnDemand.setRNumber(Room obj, int index) {
        int rNumber = index;
        obj.setRNumber(rNumber);
    }
    
    public void RoomDataOnDemand.setRState(Room obj, int index) {
        RoomState rState = RoomState.class.getEnumConstants()[0];
        obj.setRState(rState);
    }
    
    public void RoomDataOnDemand.setRType(Room obj, int index) {
        RoomType rType = RoomType.class.getEnumConstants()[0];
        obj.setRType(rType);
    }
    
    public Room RoomDataOnDemand.getSpecificRoom(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Room obj = data.get(index);
        Long id = obj.getId();
        return Room.findRoom(id);
    }
    
    public Room RoomDataOnDemand.getRandomRoom() {
        init();
        Room obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Room.findRoom(id);
    }
    
    public boolean RoomDataOnDemand.modifyRoom(Room obj) {
        return false;
    }
    
    public void RoomDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Room.findRoomEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Room' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Room>();
        for (int i = 0; i < 10; i++) {
            Room obj = getNewTransientRoom(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
